# Generated by Django 2.1.1 on 2019-12-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('organization_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=13)),
                ('mail_address', models.CharField(max_length=10)),
                ('entrance_schedule', models.DateTimeField(blank=True, null=True)),
                ('exit_schedule', models.DateTimeField(blank=True, null=True)),
                ('purpose_of_admission', models.CharField(max_length=100)),
                ('application_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
